### ISSUE TITLE
2 elements have same name

### ISSUE THREAD

**Issue by Awasaky** [defold/doc#111]
https://defold.com/manuals/message-passing/#messaging-between-game-worlds
Hard to understand where is "level" because at image 2 elements have same name. I propose to rename not important part of image - game object from "level" to "floor". This makes easier to understand this part of manual.
![collection_name](https://user-images.githubusercontent.com/24850581/92411321-cc011980-f160-11ea-8a5c-8a2db9ad3f98.png)

**Comment by britzl** [comment]
This is a good point actually!

**Comment by britzl** [comment]
Fixed in commit https://github.com/defold/doc/commit/f1e071e70c05b6724f02be5da57266108f630da7
