### ISSUE TITLE
Windows Download on website leads to 404

### ISSUE THREAD

**Issue by jpeinelt** [defold/doc#166]
The link on the download page for [Windows ]( https://d.defold.com/archive/editor-alpha/dc0725b3f70d22c8e0b1ad09bfd5f4f233d7fb0f/editor-alpha/editor2/Defold-x86_64-win32.zip) results in a 404 with the following text:

```
    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: archive/editor-alpha/dc0725b3f70d22c8e0b1ad09bfd5f4f233d7fb0f/editor-alpha/editor2/Defold-x86_64-win32.zip
    RequestId: CJ2H4SJF1R4CNAH8
    HostId: V/NLDEqF31ql4e9Gfxu2g4EKqBcs9fHvYvC44QjPhjkpmr5HpOf/7nAKoj8AqO8Gzm05DFBS4lo=
```

**Comment by britzl** [comment]
@jpeinelt I'm sorry, but where exactly did you find the broken URL?

The Windows download links on both www.defold.com/download and d.defold.com seem to be working.

**Comment by jpeinelt** [comment]
Very strange, after your feedback (thanks!!) I deleted all browser cache and now it seems to work fine. Sorry for the inconvenience!
