### ISSUE TITLE
"Resources and spawning" manual is just a stub, possibly stale?

### ISSUE THREAD

**Issue by stephen-james** [defold/doc#226]
As a defold newbie, I was looking to see how to make my primary game object spawn bullets and came across this stub:

https://github.com/defold/doc/blob/master/docs/en/manuals/spawning.md

It doesn't seem like a complete doc, and is not referenced from https://github.com/defold/doc/blob/master/docs/en/en.json

I have a feeling its been left in by mistake, but would be a great manual to have for newcomers! I don't know enough yet to contribute a doc completion (yet :D), but wanted to report it!

**Comment by britzl** [comment]
> I have a feeling its been left in by mistake, but would be a great manual to have for newcomers!

Yep, it has probably been left by mistake. If you are looking for a manual on spawning objects I suggest that you take a look at the factory manual:

https://defold.com/manuals/factory/

**Comment by britzl** [comment]
Thanks for reporting this by the way!
