### ISSUE TITLE
Rendering issue on materials pages

### ISSUE THREAD

**Issue by Palisand** [defold/doc#245]
https://defold.com/manuals/material/
<img width="736" alt="Screen Shot 2022-03-23 at 10 23 52 PM" src="https://user-images.githubusercontent.com/4138177/159829486-1096ae31-8df1-4c81-81bd-8b227b7a9097.png">

In [Typora](https://typora.io/), it looks fine:
<img width="807" alt="Screen Shot 2022-03-23 at 10 25 04 PM" src="https://user-images.githubusercontent.com/4138177/159829641-92aeb729-603e-426b-8f82-f3d90a0cf5c7.png">

I've removed the line break in the hopes that will get it to render properly on the defold docs site:
<img width="804" alt="Screen Shot 2022-03-23 at 10 25 32 PM" src="https://user-images.githubusercontent.com/4138177/159829728-90b1ea41-b845-4a20-9e77-d022c83d2ec3.png">

```diff
diff --git a/docs/en/manuals/material.md b/docs/en/manuals/material.md
index f207477..58950d7 100644
--- a/docs/en/manuals/material.md
+++ b/docs/en/manuals/material.md
@@ -69,7 +69,9 @@ CONSTANT_TYPE_NORMAL

 CONSTANT_TYPE_USER
 : A vector4 constant that you can use for any custom data you want to pass into your shader programs. You can set the initial value of the constant in the constant definition, but it is mutable through the functions [go.set()](/ref/stable/go/#go.set) / [go.animate()](/ref/stable/go/#go.animate). You can also retrieve the value with [go.get()](/ref/stable/go/#go.get). Changing a material constant of a single component instance [breaks render batching and will result in additional draw calls](/manuals/render/#draw-calls-and-batching).
-<br>Example:
+
+Example:
+
 ```lua
 go.set("#sprite", "tint", vmath.vector4(1,0,0,1))
```

Should I open a PR for this? I will make the change to the same page on other languages.

**Comment by britzl** [comment]
Thank you for reporting this! I will apply the changes myself this time, but thank you for the offer to create a PR!
