### ISSUE TITLE
.scss and .css writing mistakes in editor-styling.md

### ISSUE THREAD

**Issue by kiyomasa-slotet** [defold/doc#309]
Line 52: 
> As an example, if you add this to your custom `editor.scss` stylesheet in `.defold` folder in user home:  

Line 100: 
> The main font is defined in a root element which makes it quite easy to replace the font in most places. Add this to your `editor.scss`:

These `editor.scss` should be written as `editor.css`.

**Comment by britzl** [comment]
Thanks!
