### ISSUE TITLE
Vertically centered navbar?

### ISSUE THREAD

**Issue by mikatuo** [defold/doc#311]
Not sure if it's intentional... reporting it just in case.

The navbar content is not vertically centered, it is missing bottom padding.

![Carnac_LzUdfDEufM](https://user-images.githubusercontent.com/7230306/209452228-73bedbba-4a6f-49a5-8f3e-8f8a162f4803.png)

**Comment by mikatuo** [comment]
/tutorials/ page navbar also looks a bit off

![image](https://user-images.githubusercontent.com/7230306/209452595-6e3bafc5-58cf-4d1d-9dd3-9cff056ee417.png)

**Comment by britzl** [comment]
Fixed in https://github.com/defold/defold.github.io/commit/a5b10c8e0f5c938c583d4e971e8a0e5621bdf1ee
