### ISSUE TITLE
Outdated links in Manuals > Workflow > Writing Code

### ISSUE THREAD

**Issue by mikatuo** [defold/doc#359]
## Where

https://defold.com/manuals/writing-code/#using-an-external-code-editor

## What

> The Defold community has created auto-complete plugins for popular editors such as [Atom](https://atom.io/packages/defold-ide), [Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=selimanac.defold-vsc-snippets) and [Sublime](https://forum.defold.com/t/full-autocomplete-defold-api-for-sublime-text-3/10910). In addition to these there is also API reference packages for [Dash and Zeal](https://forum.defold.com/t/defold-docset-for-dash/2417).

"Atom" link redirects to "Sunsetting Atom" post.
"Visual Studio Code" shows "404".

**Comment by britzl** [comment]
I updated that page earlier today without knowing that you had posted this issue! 👍  Closing.
