### ISSUE TITLE
The runner tutorial hero collision shape position does not match the sprite position

### ISSUE THREAD

**Issue by PaulPorthouse** [defold/doc#370]
When you play the runner game, it appears that sometime when you jumop, you catch onto the platforms, even though you appear to be above them and should not. This appears to be due to the fact that the spine animation appears to jump higher than the collision box. I have recorded a short clip with Physics debugging enabled to show the problem. This is taken from the finished game which was downloaded from GitHub.
https://youtu.be/UVI3ggu33C4

In my test project you can see the same issue, but I have placed a small red box where the GameObject origin is, which seems to indicate that it's the animation that's out of position.
![image](https://github.com/defold/doc/assets/8049270/86e1e49c-feaf-44e2-b28a-b7d13855d53a)

Is there anything that can be done for this?

**Comment by britzl** [comment]
Ah, this is caused by the fact that the Spine jump animation itself includes vertical movement of the model. We fairly recently changed from an old Frog model to the official Spineboy and didn't consider this change. The solution would be to modify the spine scene and remove the vertical movement of the model in the jump animation.

**Comment by britzl** [comment]
Could you please share the modified file here?

**Comment by PaulPorthouse** [comment]
Of course
[hero.spinejson.zip](https://github.com/defold/doc/files/13864613/hero.spinejson.zip)

**Comment by britzl** [comment]
Thanks. I updated the sample project.

https://github.com/defold/sample-runner/commit/9140aa2e233918dc6211c2b5760931b92c0a485b
