### ISSUE TITLE
Can I add chinese language to new folder?

### ISSUE THREAD

**Issue by Sun-FreePort** [defold/doc#53]
I want to translation tutorial to chinese.

If i can, what's the folder name? 

( I think `zh-cn` is right )

**Comment by AGulev** [comment]
Hi, 
Yes, I think you are right.
Also you should add new language into https://github.com/defold/doc/blob/master/docs/languages.json
👍

**Comment by Sun-FreePort** [comment]
Nice, I will one by one translate in my spare time.

**Comment by Sun-FreePort** [comment]
Hi, @AGulev 

i have not translated such a large document.

Can i submit all file? i think this is not conducive to code review.

or, *translate some page* => *submit PR* => *translate again*, them can create very many PR, is this correct?

**Comment by AGulev** [comment]
Hi @Sun-FreePort ,
Both options are great. Feel free to do it in a way that easier for you.
In my opinion, it's a bit easier to do step-by-step, but it's up to you.
