### ISSUE TITLE
Should mention Sounds and ParticleFX continuing after deletion.

### ISSUE THREAD

**Issue by rgrams** [defold/doc#55]
If you delete a game object with a playing Sound or ParticleFX component, the sound/effect will continue until its playback ends, even though it was theoretically destroyed. Maybe this is already written somewhere, but a brief search in the API ref and manuals for Sounds and ParticleFX did not turn up anything. 

This caused a bit of confusion in this thread: https://forum.defold.com/t/collection-proxy-doesnt-reset/53986

**Comment by britzl** [comment]
Added one sidenote in the sound manual: https://www.defold.com/manuals/sound/#_playing_the_sound
Added one sidenote in the particle effect manual: https://www.defold.com/manuals/particlefx/#_controlling_a_particle_effect

Will add something to the API ref as well.
