### ISSUE TITLE
About free provisioning profile on iOS

### ISSUE THREAD

**Issue by mosmetro** [defold/doc#86]
From https://github.com/defold/doc/blob/master/docs/en/manuals/ios.md:
"This provision file can be used together with your code signing identity to sign apps in Defold for one week, **for _one_ device. There is no way to add additional device UDIDs to this generated provisioning profile.**"
Not really. I was able to register 3 devices and maybe could have even more. I was not able to figure out how many devices the free profile supports, but I think it's 100, just like with a paid account.

**Comment by britzl** [comment]
Ah, maybe Apple has changed this then?
