### ISSUE TITLE
Stencil test before drawing gui in default render script

### ISSUE THREAD

**Issue by Sayuris1** [defold/doc#91]
I guess it's used for gui clipping. Should be mentioned in the manual

**Comment by britzl** [comment]
You mean this section of the manual? https://defold.com/manuals/render/#the-render-script

**Comment by Sayuris1** [comment]
This section:

![Capture](https://user-images.githubusercontent.com/56207443/87233937-b2e42280-c3d4-11ea-9038-09fe81581a82.PNG)

I just started studying OpenGL and wanted to learn why defold uses stencil test here.
